[package]
name = "thaiengine"
version = "0.1.0"
authors = ["Manatsawin Hanmongkolchai <manatsawin+git@gmail.com>"]
build = "build.rs"

[dependencies]
radix_trie = "*"
encoding = "0.2.32"
stopwatch = "0.0.6"
